// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg0568t5EaObQ9Z4rnXRsypd9O8W4Xl0c',
    appId: '1:893791333046:web:b20ca2f0a59ebdadc25417',
    messagingSenderId: '893791333046',
    projectId: 'service-provider-app-48875',
    authDomain: 'service-provider-app-48875.firebaseapp.com',
    storageBucket: 'service-provider-app-48875.appspot.com',
    measurementId: 'G-5DZ08YWVE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJobIHJcl-kYO8MINjx4V_bp3UXiVzIFA',
    appId: '1:893791333046:android:7a42cae8a1b78ef8c25417',
    messagingSenderId: '893791333046',
    projectId: 'service-provider-app-48875',
    storageBucket: 'service-provider-app-48875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaK6i6g7qhdXrGzdv7AOxT-X8n15HbGfI',
    appId: '1:893791333046:ios:56592ea1fbff8acec25417',
    messagingSenderId: '893791333046',
    projectId: 'service-provider-app-48875',
    storageBucket: 'service-provider-app-48875.appspot.com',
    iosClientId: '893791333046-c8v7b90msbpni4ipog6o5svla8v2ts06.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodseller.vishakha1122',
  );
}
